-- vim.cmd("highlight @markup.heading.1.markdown guifg=#82aaff")
-- vim.cmd("highlight @markup.heading.2.markdown guifg=#ffc777")
-- vim.cmd("highlight @markup.heading.3.markdown guifg=#4fd6be")
-- vim.cmd("highlight @markup.heading.4.markdown guifg=#c3e88d")
-- vim.cmd("highlight @markup.heading.5.markdown guifg=#c099ff")
-- vim.cmd("highlight @markup.heading.6.markdown guifg=#fca7ea")
-- vim.cmd("highlight RenderMarkdownH1Bg guibg=#273849")
-- vim.cmd("highlight RenderMarkdownH2Bg guibg=#252a3f")
-- vim.cmd("highlight RenderMarkdownH3Bg guibg=#252a3f")
-- vim.cmd("highlight RenderMarkdownH4Bg guibg=#3a273a")
-- vim.cmd("highlight RenderMarkdownH5Bg guibg=#394b70")
-- vim.cmd("highlight RenderMarkdownH6Bg guibg=#394b70")

-- TODO: colorscheme (~/projects/doom)
-- -- vim.cmd("highlight NormalFloat guibg=#394b70")
vim.api.nvim_set_hl(0, "lualine_a_normal", { fg = "#1d202f", bg = "#7aa2f7", bold = true })
vim.api.nvim_set_hl(0, "lualine_a_insert", { fg = "#1d202f", bg = "#9ece6a", bold = true })
vim.api.nvim_set_hl(0, "lualine_a_visual", { fg = "#1d202f", bg = "#bb9af7", bold = true })
vim.api.nvim_set_hl(0, "lualine_a_replace", { fg = "#1d202f", bg = "#f7768e", bold = true })
vim.api.nvim_set_hl(0, "lualine_a_command", { fg = "#1d202f", bg = "#e0af68", bold = true })
--
-- vim.cmd("highlight LspReferenceRead guifg=none guibg=#283347")
-- vim.cmd("highlight LspReferenceWrite guifg=none guibg=#283347")
-- vim.cmd("highlight LspReferenceText guifg=none guibg=#283347")
-- vim.cmd("highlight MatchParen cterm=bold,underline gui=none guifg=#ec7279 guibg=#455574")
-- vim.cmd("highlight Function ctermfg=14 gui=bold guifg=#db8ffc")
--
-- vim.cmd("highlight LspReferenceRead guifg=none guibg=#283347")
-- vim.cmd("highlight LspReferenceWrite guifg=none guibg=#283347")
-- vim.cmd("highlight LspReferenceText guifg=none guibg=#283347")
-- vim.cmd("highlight MatchParen cterm=bold,underline gui=none guifg=#ec7279 guibg=#455574")
-- vim.cmd("highlight Function ctermfg=14 gui=bold guifg=#db8ffc")
-- vim.cmd("highlight Visual ctermfg=none ctermbg=none guibg=#252a3f guifg=#bab6b6")
-- -- vim.cmd("highlight Float guibg=#1c1f24 guifg=#bb9af7")
--
-- -- vim.cmd("highlight Keyword ctermfg=14 gui=bold guifg=#db8ffc")
-- -- vim.cmd("highlight String ctermfg=10 guifg=#d38d5a")
