vim.pack.add({ "https://github.com/stevearc/quicker.nvim" })
local quicker = require("quicker")
quicker.setup({})
vim.keymap.set("n", "Q", function()
  quicker.toggle({ height = 10 })
end, { desc = "Toggle quickfix" })
vim.keymap.set("n", "<leader>qx", function()
  quicker.toggle({ loclist = true, height = 10 })
end, { desc = "Toggle loclist" })
